spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/backend-cicd
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:backend-cicd
  jpa:
    hibernate:
      ddl-auto: create
